
  !!io.hawkcd.model.configuration.Configuration
  artifactsDestination: Artifacts
  databaseConfigs:
    REDIS:
      host: localhost
      name: hawkdb
      password:
      port: 6379
      username:
    MONGODB:
      host: localhost
      name: hawkmongo
      password: admin
      port: 27017
      username: admin
  databaseType: MONGODB
  materialTrackerPollInterval: 2
  materialsDestination: Materials
  oAuthProviderConfigs:
    GITHUB:
      accessTokenUrl:
      clientId:
      clientSecret:
      isEnabled: false
  pipelineSchedulerPollInterval: 2
  serverHost: localhost
  serverId:
  serverPort: 8080